<?php
	$baseDir = '../../../';                // root directory
	$includesDir = $baseDir . 'oxincludes';
	include($baseDir . 'classictheme.inc');

	$SECTION = 'resources';
	$CUSTOMBREADCRUMB = '<li>&nbsp;&raquo;&nbsp;</li><li><a href="/network-management/">Resources</a></li><li>&nbsp;&raquo;&nbsp;</li><li><a href="/network-management/performance-management/">Performance Management</a></li><li>&nbsp;&raquo;&nbsp;</li><li><a href="/network-management/performance-management/open-source/">Open Source</a></li>';
	$SELECTED = "";
?>